name: Deploy social-frontend

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}                       
            - name: Build Docker Image
              run: docker build -t qraztec/social_frontend .
            - name: Publish Image to docker hub
              run: docker push qraztec/social_frontend:latest 

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull qraztec/social_frontend:latest 
            - name: Delete old container
              run: docker rm -f social-frontend-container
            - name: Run Docker Container
              run: docker run -d -p 3000:80 --name social-frontend-container qraztec/social_frontend


 
        